os: linux
dist: bionic
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"

# command to install dev dependencies
install:
  - pip install tox-travis codecov

# command to run tests
script:
  - tox -e lint
  - tox

after_success:
    - bash <(curl -s https://codecov.io/bash)

jobs:
  fast_finish: true
  allow_failures:
    - python: "nightly"

notifications:
  irc:
    channels:
      - "irc.freenode.org#code-hell"
      - "irc.freenode.org#allieae"
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
