# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  global:
    PYTHONIOENCODING: utf-8
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python39-x64"

## Before repo cloning
init:
  ## without this, temporary directory could be created in current dir
  ## which will make some tests fail.
  - mkdir C:\TMP
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -V

## After repo cloning
install:

build: false

## Before tests
before_test:
  - pip install -e .[test,ci]
  - pip install codecov

## Custom test script
test_script:

  ## Fail early on big problems
  - "python src\\gitchangelog\\gitchangelog.py --debug"
  - "python src\\gitchangelog\\gitchangelog.py --debug HEAD^^..HEAD"

  ## real tests
  - nosetests -sx .

  ## installable
  - pip install .
  - gitchangelog --debug
  - "gitchangelog HEAD^^..HEAD"

after_test:
  - "codecov & REM  #dovis: ignore"
