name: Release

on:
  push:
    # release on tag push
    tags:
      - '*'

jobs:
  create_wheels:
    name: Build wheels on ${{ matrix.os }} for Python
    runs-on: ${{ matrix.os }}
    env:
      MANYLINUX2010_X86_64_TAG: "2020-12-03-912b0de"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install twine build
          pip install mako
          pip install git+https://github.com/sarnold/pystache@0.5.4-2

      - name: Build wheels
        run: |
          python -m build -s
          python setup.py bdist_wheel
          twine check dist/*

      - uses: actions/upload-artifact@v2
        # Prevent the job from failing when the upload artifact step
        # fails (the network infrastructure is not very reliable yet)
        continue-on-error: true
        with:
          name: wheels
          path: ./dist/*.whl

  create_release:
    name: Create Release
    needs: [create_wheels]
    runs-on: ubuntu-20.04

    steps:
      - name: Get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo ${{ env.VERSION }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # somehow gitchangelog cannot see the local tag
      - run: |
          git describe --tags
          #git fetch --tags

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.7

      - name: Install myself
        run: |
          pip install .

      - uses: actions/download-artifact@v2
        with:
          name: wheels

      - name: Generate changes file
        env:
          GITCHANGELOG_CONFIG_FILENAME: "src/gitchangelog/gitchangelog.rc.github.release"
        run: |
          bash -c './gitchangelog $(git tag -l | tail -n2 | head -n1)..${{ env.VERSION }} > CHANGES.md'

      - name: Create draft release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: CHANGES.md
          draft: false
          prerelease: false
          files: ./git*.whl
